### ISSUE TITLE
Task 011 - Administrator dashboard

### ISSUE THREAD

**Issue by cesargaldor** [cesargaldor/D02-Data-model-E5.03#11]

**Comment by Alvaroyiyo** [comment]
The system must handle administrator dashboards with the following indicators: 
- Total number of components;
- Average, deviation, minimum, and maximum retail price of components, grouped by technology and currency;
- Total number of tools; 
- Average, deviation, minimum, and maximum retail price of tools, grouped by currency;
- Total number of proposed/accepted/denied patronages; average, deviation, minimum, and maximum budget of proposed/accepted/denied patronages.
